spring:
  datasource:
    url: jdbc:postgresql://dpg-d00n59i4d50c73cg65l0-a.oregon-postgres.render.com/venditaprodotti_db_hu9p
    username: venditaprodotti_db_hu9p_user
    password: VLUC5HWZND3w2EAaToEl2Yzg7hlSZiU6
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

urlBackend: https://venditaprodotti.onrender.com
directoryFile: C:\\Users\\manu9\\Desktop