spring:
  profiles:
    active: prod

sendgrid:
  api:
    key: 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

bulkgate:
  api:
    url: https://portal.bulkgate.com/api/1.0/simple/transactional
    application_id: 34487
    application_token: vrIhIMxN2SzQuUXWVwEYMI25v6nfNv8PGfRCVAfFEbp8YvpHMZ

authCode: 1feac177-a7ad-4052-8ca5-2f65b9cfd8db
companyEmail: manu91eo@storeottana.it
urlSiteWeb: https://storeottana.it

jwt:
  secret: kuRtK3874x8SDPYew6E8K8GHA0pe6LznmF6lfqzuVo9cEXJI

stripe:
  secret:
    key: sk_test_51QxEIQAY23rh6peRdHRWiIJa3K6YijEIhYbWZkDlyVAWIQRtVCuwcYrXxj5e3Rimb4prhRwoXesmxsfCVD3O0Mt000PqSFV4ly
    authKey: whsec_qnnD3XmZHlJ1vJlrAGFdquwvO4MSWyr3
vero_key: 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