spring:
  datasource:
    url: jdbc:postgresql://dpg-cvk3asruibrs739soafg-a.oregon-postgres.render.com/inserzioni
    username: inserzioni_user
    password: nmoKTTqXtY9oivQbsRFPRd7Ab4mNNIQ4
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

urlBackend: https://venditaprodotti.onrender.com
directoryFile: C:\\Users\\manu9\\Desktop