server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paginaprodotto
    username: root
    password: 151002
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

urlBackend: http://localhost:8080
directoryFile: C:\\Users\\manu9\\Desktop