spring:
  datasource:
    url: jdbc:postgresql://dpg-cvrom10gjchc73betgjg-a/venditaprodotti_db
    username: venditaprodotti_db_user
    password: gon1yrA01EhVmDv5CdvZdycIBOd5MUBV
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

urlBackend: https://venditaprodotti.onrender.com
directoryFile: x