spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paginaprodotto
    username: root
    password: 151002
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

directoryFile: C:\\Users\\manu9\\Desktop

JWT:
  Secret: 2zqxyz86qaazzoyp08hj8wmq4nzqtxmiw9i525qqsu894y3ees

stripe:
  secret:
    key: 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
