spring:
  profiles:
    active: prod

directoryFile: C:\\Users\\manu9\\Desktop

JWT:
  Secret: 2zqxyz86qaazzoyp08hj8wmq4nzqtxmiw9i525qqsu894y3ees

stripe:
  secret:
    key: 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