spring:
  datasource:
    url: jdbc:postgresql://dpg-cvqq2vuuk2gs73bacpbg-a/venditaprodotti
    username: venditaprodotti_user
    password: vU1AV87ugLBNef3pQYPjf5UHVXL3SovN
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update

urlBackend: https://venditaprodotti.onrender.com
directoryFile: x