spring:
  profiles:
    active: dev

sendgrid:
  api:
    key: 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

bulkgate:
  api:
    url: https://portal.bulkgate.com/api/1.0/simple/transactional
    application_id: 34487
    application_token: vrIhIMxN2SzQuUXWVwEYMI25v6nfNv8PGfRCVAfFEbp8YvpHMZ

authCode: 1feac177-a7ad-4052-8ca5-2f65b9cfd8db
companyEmail: manu91eo@storeottana.it

JWT:
  Secret: 2zqxyz86qaazzoyp08hj8wmq4nzqtxmiw9i525qqsu894y3ees

stripe:
  secret:
    key: sk_test_51QxEIQAY23rh6peRdHRWiIJa3K6YijEIhYbWZkDlyVAWIQRtVCuwcYrXxj5e3Rimb4prhRwoXesmxsfCVD3O0Mt000PqSFV4ly
    authKey: whsec_qnnD3XmZHlJ1vJlrAGFdquwvO4MSWyr3
vero_key: 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